name: Test suite workflow

on:
  pull_request:
    branches:
      - 'master'

jobs:
  Running-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.8", "3.10"]
        django: ["32"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependency
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/test.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dev Requirements
        run: |
          make install-dev-dependencies
      - name: Run Python Tests
        run: |
            export TOXENV=${TOX_ENV//./}
            make run-tests
        env:
          TOX_ENV: py${{matrix.python-version}}-django${{matrix.django}}
